### ISSUE TITLE
Makefile capitalization error

### ISSUE THREAD

**Issue by faragher** [liberatedsystems/RNode_Firmware_CE#44]
Cloned the repo (~20SEP2024) and ran make. Make could not find the RNode_Firmware_CE.ino, since it was looking for an upper-case version and the repo had a lower case version. Knock-on effects occurred due to other portions of the make file expected similar capitalization.

Since the Github repo itself has it capitalized, I attempted to reproduce, and determined that the make file uses the capitalization of the base directory to determine the name of the .ino it's looking for. Given that it's possible someone, like myself, would type in the repo manually, place it in a custom folder, etc. it's worth tracking down why it does this and directly targeting the name, not the parent directory's name.

**Comment by jacobeva** [comment]
Okay, I think I get what you mean now. This is an arduino-specific thing if I'm correct, you will likely have the same issue with the original `RNode-Firmware` if you tried to clone and build that too. The parent directory name *has* to be the same as the sketch filename. I can't do anything about that as far as I'm aware.

Out of curiousity, how are you managing to have the case for the repo incorrect when you clone it? I remember you mentioning windows to me personally, does the windows version of git not preserve case when cloning repos?

**Comment by faragher** [comment]
Debian. It clones the repo as typed, not as stored in the Repo itself.

Arduino really does have the dumbest assumptions.

**Comment by jacobeva** [comment]
Oh I see, when you cloned, did you clone it like `git clone https://github.com/liberatedsystems/rnode_firmware_ce`?

**Comment by faragher** [comment]
Correct. In testing I cloned deliberately using `RNode_firmware_CE` and figured out the problem that way, since it looked for that exact pattern.

Anyway, if it's not on your end, it's simply something to be aware of, unless there's some way to force Arduino to do something different.
