### ISSUE TITLE
ESP32 BLE support

### ISSUE THREAD

**Issue by Marc12O** [liberatedsystems/RNode_Firmware_CE#8]
Heltec WiFi LoRa 32 V3 board, the latest V3.1 board, has no discoverable Bluetooth, with RNode firmware 1.72

On my phone, when trying to add a BT device and pair it, nothing shows up, I did activate BT with rnodeconf -b and -p

Other boards like TTGO work fine

The rest of functionality works fine, e.g. USB connection, LoRa :-)

Thank you for RNode!

![2024-05-31 11 03 38](https://github.com/liberatedsystems/RNode_Firmware_CE/assets/2293415/0d7659f4-05da-44fc-9d6e-22b541b2a488)

![2024-05-31 11 03 44](https://github.com/liberatedsystems/RNode_Firmware_CE/assets/2293415/d844361a-8002-4990-97ae-d3803d444d34)

**Comment by jacobeva** [comment]
From looking at our codebase currently, it looks to me that this board uses BLE, but there is no driver written for it yet on ESP32 platforms.

**Comment by jacobeva** [comment]
As of current I do not possess any of these boards, or any ESP32 device which has BLE capability. You are welcome to attempt the implementation of this feature yourself (and I will provide you direction). If not, a hardware donation would allow me to implement it when I have time :)

**Comment by jacobeva** [comment]
The board arrived a couple days ago. Development will begin when I have time.

**Comment by jacobeva** [comment]
Progress is being made on this front, I have just managed to get a basic connection working over BLE to my computer. Now to iron out bugs and get serial working properly...

**Comment by jacobeva** [comment]
My changes have been pushed to the `esp32-ble` branch on this repo. For anyone who may have time, testing would be appreciated. Currently there's a crash which occurs after some time when receiving / sending packets, probably memory related. Also, the throughput is bottlenecked by BLE quite heavily, I will work on that also. https://github.com/liberatedsystems/RNode_Firmware_CE/tree/esp32-ble

**Comment by macvenez** [comment]
Hi, I'm trying to enable ble, I checked out this branch, compiled and uploaded it (thanks to your help in the other discussion :-) ), anyway when the device boots up I start scanning from my phone and nothing shows up as bluetooth device. Do I have to enable it from the device somewhere?
Still thanks for these sunday tests

**Comment by jacobeva** [comment]
`rnodeconf -b /dev/ttyUSB0` to enable bluetooth :)

**Comment by jacobeva** [comment]
You need to run `rnodeconf -p /dev/ttyUSB0` in order to enable pairing also.

**Comment by jacobeva** [comment]
Sideband doesn't support BLE yet. That is actively being worked on.

**Comment by macvenez** [comment]
Alright, that's what I was missing then, thanks!
How are you testing ble connectivity?

**Comment by jacobeva** [comment]
Using `ble-serial` on my desktop, currently :)

**Comment by jacobeva** [comment]
Mark actually beat me to it on this one, see https://github.com/markqvist/RNode_Firmware/releases/tag/1.75. This will be merged into the CE repo soon.

**Comment by jacobeva** [comment]
This has been merged into the dev branch and will be in a release soon
